### ISSUE TITLE
Language Varieties

### ISSUE THREAD

**Issue by jspitz** [SFr682k/datetime2-german#1]
Thanks for taking maintenance of this package. Following your request, I just want to record that there are in fact differences in the formats of the three (not two) German varieties, de_DE, de_AT and de_CH. E.g., Austrian month name "Jänner" and abbreviation "Jän." (see also Austrian babel and polylgossia), Swiss German time separator (dot, not colon, i.e., 20.15, not 20:15).

BTW in the manual you write that "you are only capable of standard German". That should read "German Standard German", since there is in fact also Swiss and Austrian Standard German. See https://en.wikipedia.org/wiki/German_language#Varieties_of_Standard_German

**Comment by SFr682k** [comment]
Thanks for the remark.
I'll work on this

**Comment by jspitz** [comment]
Thanks! Small issue in `DTMdeATshortmonthname`:
`J\protect\"n.%` -> `J\protect\"an.%`

---

Side note: the DIN 5008 [1] proposes these abbreviations in contrast to those used by `datetime-german` currently:

- Jan., **Feb.**, Mär./März, **Apr.**, Mai, Jun./Juni, Jul./Juli, Aug., Sept., Okt., Nov., Dez.

ÖNORM A 1080 [2] notes that abbreviations for months should generally be avoided, but these abbreviations seem to be favored, if any, for Austrian (see [4]):
- Jän., Feb., März, Apr., Mai, Juni, Juli, Aug., Sep./Sept., Okt., Nov., Dez.

The Swiss regulations (Weisungen der Bundeskanzlei [3]) have this:
- Jan., **Febr. [falsch: Feb.]**, März, April, Mai, Juni, Juli, Aug., Sept., Okt., Nov., Dez.

[1] https://www.din-5008-richtlinien.de/startseite/datum/
[2] https://www.austrian-standards.at/fileadmin/user/bilder/content-infopedia/ENTWURF_%C3%96NORM-A1080_2014-03_ANSICHTSexemplar.pdf
[3] https://www.bk.admin.ch/dokumentation/sprachen/04915/05016/index.html?lang=de
[4] http://www.lbs-lochau.at/fileadmin/_migrated/content_uploads/Text_%C3%96NORM__A__1080.pdf
